export enum RoutesApp {
  LOGIN = 'login',
  REQUEST_MANAGER = 'request-manager',
  APPLICANT_TYPE = 'applicant-type',
  REQUEST_TYPE = 'request-type',
  APPLICANT_REQUEST = 'applicant-request',
  MODALITY = 'modality',
  SEARCH_REQUEST = 'search-request',
  LOGOUT = 'logout',
  USERS_LIST = 'db/users',
  ALL_REQUESTS = 'request/getall',
  CREATE_USER = 'user/create',
  INACTIVATE_USER = 'user/in-activate',
  INVISIBLE_USER = 'user/in-visible',
  APPLICANT_TYPE_LIST = 'db/applicant_type',
  INACTIVATE_APPLICANT = 'applicant/in-activate',
  REQUEST_TYPE_LIST = 'db/request_type',
  INACTIVATE_REQUEST = 'request/in-activate',
  APPLICANTYPE_REQUESTYPE = 'applicants/requests/association',
  ASSOCIATE_REQUEST_APPLICANT = 'associate/applicant/request',
  INACTIVE_ASSOCIATE_REQUEST_APPLICANT = 'association/applicant/request/in-activate',
  CREATE_APPLICANT_TYPE = 'applicant/create',
  CREATE_REQUEST_TYPE = 'requestype/create',
  MODALITY_LIST = 'db/modalities',
  CREATE_MODALITY = 'modality/create',
  UPDATE_MODALITY = 'modality/update',
  INACTIVATE_MODALITY = 'modality/in-activate',
}
