export enum RoutesApp {
  LOGIN = 'login',
  REQUEST_MANAGER = 'request-manager',
  APPLICANT_TYPE = 'applicant-type',
  REQUEST_TYPE = 'request-type',
  APPLICANT_REQUEST = 'applicant-request',
  MODALITY = 'modality',
  CATEGORY = 'category',
  SEARCH_REQUEST = 'search-request',
  REQUEST_REPORT = 'request-report',
  LOGOUT = 'logout',
  CREATE_REQUEST = 'create-request',
  REQUEST_DETAILS = 'request-details',
}
export enum EndPointRoute {
  USERS_LIST = 'db/users',
  ALL_REQUESTS = 'request/getall',
  CREATE_USER = 'user/create',
  ASSIGN_USER_TO_REQUEST = 'request/assignuser',
  INACTIVATE_USER = 'user/in-activate',
  INVISIBLE_USER = 'user/in-visible',
  APPLICANT_TYPE_LIST = 'db/applicant_type',
  INACTIVATE_APPLICANT = 'applicant/in-activate',
  REQUEST_TYPE_LIST = 'db/request_type',
  INACTIVATE_REQUEST = 'request/in-activate',
  APPLICANTYPE_REQUESTYPE = 'applicants/requests/association',
  ASSOCIATE_REQUEST_APPLICANT = 'associate/applicant/request',
  INACTIVE_ASSOCIATE_REQUEST_APPLICANT = 'association/applicant/request/in-activate',
  CREATE_APPLICANT_TYPE = 'applicant/create',
  MODIFY_APPLICANT_TYPE = 'applicantype/modify',
  CREATE_REQUEST_TYPE = 'requestype/create',
  MODIFY_REQUEST_TYPE = 'requestype/modify',
  MODALITY_LIST = 'db/modalities',
  CREATE_MODALITY = 'modality/create',
  UPDATE_MODALITY = 'modality/modify',
  INACTIVATE_MODALITY = 'modality/in-activate',
  CATEGORY_LIST = 'db/categories',
  CREATE_CATEGORY = 'category/create',
  INACTIVATE_CATEGORY = 'category/in-activate',
  UPDATE_CATEGORY = 'category/modify',
  REQUEST_BY_APPLICANT = '/requeststypes/by',
}
